spring:
  application.name: Online Bookstore Management System
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: password
  h2:
    console:
      enabled: true
server:
  error:
    include-binding-errors: always
    include-message: always
